/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab1;

public class Main{

    public static void main(String[] args){
        MainApp app = new MainApp();
        app.start(); // start the game
    }

}
