/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab1;

import com.jme3.math.*;
import java.io.*;
import java.util.Scanner;
import java.lang.Math;

public class Physics{
    
    private Vector3f jupiterPosition;
    private Vector3f voyagerPosition;
    private Vector3f directVector;
    
    private final static float G = 0.05f;
    private final static float jupiterRadius = 4.4f;
    private final static float jupiterWeight = 30000f;
    
    
    public void inputVals(String path)
    {
        File file = new File(path);
        try{
            Scanner in = new Scanner(file);
            this.jupiterPosition.x = Float.valueOf(in.next()).floatValue();
            this.jupiterPosition.y = Float.valueOf(in.next()).floatValue(); 
            this.jupiterPosition.z = Float.valueOf(in.next()).floatValue();
            this.voyagerPosition.x = Float.valueOf(in.next()).floatValue();
            this.voyagerPosition.y = Float.valueOf(in.next()).floatValue(); 
            this.voyagerPosition.z = Float.valueOf(in.next()).floatValue();
            this.directVector.x = Float.valueOf(in.next()).floatValue(); 
            this.directVector.y = Float.valueOf(in.next()).floatValue(); 
            this.directVector.z = Float.valueOf(in.next()).floatValue();
        }
        catch (FileNotFoundException ex)  
        {
        
        }
    }
    
    public Physics(){
        this.jupiterPosition = new Vector3f(0, 0, 0);
        this.voyagerPosition = new Vector3f(jupiterRadius*2f, jupiterRadius*2f, jupiterRadius*2f);
        this.directVector = new Vector3f(0,0,0);
    }
    
    public float getJupiterRadius()
    {
        return jupiterRadius;
    }
    
    public Vector3f getJupiterPosition()
    {
        return jupiterPosition;
    }
    
    public Vector3f getVoyagerPosition()
    {
        return voyagerPosition;
    }    
    
    public Vector3f getDirectVector()
    {
        return directVector;
    }
    
    public Vector3f getGravity(Vector3f newVoyagerPosition)
    {
        voyagerPosition = newVoyagerPosition;
        Vector3f delta = new Vector3f(0, 0, 0);
        delta.x = jupiterPosition.x - voyagerPosition.x;
        delta.y = jupiterPosition.y - voyagerPosition.y;
        delta.z = jupiterPosition.z - voyagerPosition.z;
    
        float len = (float)Math.sqrt((double) (delta.x*delta.x + delta.y*delta.y + delta.z*delta.z));
        float accel = G*jupiterWeight/(len*len);
        Vector3f gravity = new Vector3f(accel*delta.x/len, accel*delta.y/len, accel*delta.z/len);
        return gravity;
    }
}
