/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab1;

import com.jme3.math.Vector3f;
import java.io.*;
import java.util.Scanner;

public class Physics{
    
    private Vector3f jupiterPos;
    private Vector3f voyagerPos;
    private Vector3f directVector;
    private final static float jupiterWeight = 1.898e27f;  
    private float voyagerWeight;
    
    
    private void inputVals()
    {
        this.jupiterPos = new Vector3f();
        this.voyagerPos = new Vector3f();
        this.directVector = new Vector3f();
        File file = new File("src/main/java/lab1/input.txt");
        
        try{
            Scanner in = new Scanner(file);
            this.jupiterPos.x = Float.valueOf(in.next()).floatValue();
            this.jupiterPos.y = Float.valueOf(in.next()).floatValue(); 
            this.jupiterPos.z = Float.valueOf(in.next()).floatValue();
            this.voyagerPos.x = Float.valueOf(in.next()).floatValue();
            this.voyagerPos.y = Float.valueOf(in.next()).floatValue(); 
            this.voyagerPos.z = Float.valueOf(in.next()).floatValue();
            this.directVector.x = Float.valueOf(in.next()).floatValue(); 
            this.directVector.y = Float.valueOf(in.next()).floatValue(); 
            this.directVector.z = Float.valueOf(in.next()).floatValue(); 
            this.voyagerWeight = Float.valueOf(in.next()).floatValue(); 
        }
        catch (FileNotFoundException ex)  
        {
        
        }
    }
    
    public Physics(){
        inputVals();
    }
}
